"""store the rag index in postgres

Revision ID: 2be893cc302e
Revises: bbc8267eef21
Create Date: 2026-09-03 21:17:43.396761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2be893cc302e'
down_revision: Union[str, None] = 'bbc8267eef21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_vectors',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embed_model', sa.String(length=200), nullable=False),
    sa.Column('foot', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('position_group', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_vectors_embed_model'), 'player_vectors', ['embed_model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_vectors_embed_model'), table_name='player_vectors')
    op.drop_table('player_vectors')
    # ### end Alembic commands ###
