"""player_vector metrics

Revision ID: 40e7367870b9
Revises: fd64e8bcc2e5
Create Date: 2026-09-04 19:51:42.748291
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40e7367870b9'
down_revision: Union[str, None] = 'fd64e8bcc2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_vectors', sa.Column('metrics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_vectors', 'metrics')
    # ### end Alembic commands ###
