"""competition gender

Revision ID: bd88a3f6b5d2
Revises: 6619426379c2
Create Date: 2026-09-04 09:52:29.260331
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd88a3f6b5d2'
down_revision: Union[str, None] = '6619426379c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'gender')
    # ### end Alembic commands ###
