"""player_vector nationality

Revision ID: fd64e8bcc2e5
Revises: bd88a3f6b5d2
Create Date: 2026-09-04 15:41:23.958985
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd64e8bcc2e5'
down_revision: Union[str, None] = 'bd88a3f6b5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_vectors', sa.Column('nationality', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_vectors', 'nationality')
    # ### end Alembic commands ###
